// FRONT ULTRA — command mode i18n strings (owner: command). Registered once at module load, es + en.

import { registerDictionary } from '../shared/i18n';

const es: Record<string, string> = {
  'command.kind.tank': 'División acorazada',
  'command.kind.jet': 'Escuadrón de caza',
  'command.kind.ship': 'Grupo naval',
  'command.vehicle.tank': 'CARRO DE COMBATE',
  'command.vehicle.jet': 'CAZA POLIVALENTE',
  'command.vehicle.ship': 'DESTRUCTOR',
  'command.intro.op': 'OPERACIÓN',
  'command.intro.front': 'Frente contra {enemy}',
  'command.intro.coords': '{lat} · {lon}',
  'command.intro.local': 'HORA LOCAL {time}',
  'command.objective': 'Destruye {n} unidades enemigas para romper el frente',
  'command.objective.short': 'ROMPER EL FRENTE',
  'command.objective.done': 'FRENTE ROTO',
  'command.objective.doneSub': 'El enemigo se retira. Pulsa ESC para volver al mando estratégico',
  'command.hp': 'BLINDAJE',
  'command.hp.jet': 'INTEGRIDAD',
  'command.hp.ship': 'CASCO',
  'command.ammo.ap': 'PERFORANTE',
  'command.ammo.he': 'EXPLOSIVO',
  'command.ammo.mg': 'AMETRALLADORA',
  'command.ammo.smoke': 'HUMO',
  'command.ammo.gun': 'CAÑÓN',
  'command.ammo.aam': 'MISILES IR',
  'command.ammo.flares': 'BENGALAS',
  'command.ammo.main': 'CAÑÓN 127 mm',
  'command.ammo.ssm': 'MISILES ANTIBUQUE',
  'command.ammo.ciws': 'CIWS',
  'command.reload': 'RECARGANDO',
  'command.ready': 'LISTO',
  'command.speed': 'VEL',
  'command.alt': 'ALT',
  'command.throttle': 'MOTOR',
  'command.telegraph': 'TELÉGRAFO',
  'command.tel.-1': 'ATRÁS',
  'command.tel.0': 'PARADA',
  'command.tel.1': 'AVANTE POCA',
  'command.tel.2': 'AVANTE MEDIA',
  'command.tel.3': 'AVANTE TODA',
  'command.tel.4': 'MÁXIMA',
  'command.rudder': 'TIMÓN',
  'command.range': 'DIST',
  'command.lock': 'FIJADO',
  'command.locking': 'FIJANDO',
  'command.missile': 'MISIL',
  'command.pullUp': 'REMONTA',
  'command.stall': 'VELOCIDAD BAJA',
  'command.boundary': 'ABANDONANDO LA ZONA DE COMBATE',
  'command.hit': 'IMPACTO',
  'command.kill': 'DESTRUIDO',
  'command.killF': 'DESTRUIDA',
  'command.ricochet': 'REBOTE',
  'command.youKilled': 'Has destruido: {what}',
  'command.feed.you': 'TÚ',
  'command.feed.allies': 'ALIADOS',
  'command.feed.enemy': 'ENEMIGO',
  'command.lead': 'AVANCE',
  'command.exit': 'VOLVER AL MANDO',
  'command.clickToAim': 'Haz clic para capturar el ratón',
  'command.help.tank': 'WASD conducir · Ratón apuntar · Clic disparar · Clic der. mira · 1/2 munición · Espacio ametralladora · C humo · ESC salir',
  'command.help.jet': 'Ratón dirigir · W/S potencia · A/D alabeo · Q/E guiñada · Clic cañón · Clic der. misil · F bengalas · ESC salir',
  'command.help.ship': 'W/S telégrafo · A/D timón · Ratón apuntar · Clic cañón · Clic der. misil antibuque · ESC salir',
  'command.destroyed': 'VEHÍCULO DESTRUIDO',
  'command.destroyedSub': 'La unidad se ha perdido en combate',
  'command.debrief': 'INFORME DE COMBATE',
  'command.debrief.kills': 'Unidades enemigas destruidas',
  'command.debrief.troops': 'Bajas enemigas en este frente',
  'command.debrief.time': 'Duración',
  'command.debrief.acc': 'Precisión',
  'command.debrief.status': 'Estado de la unidad',
  'command.debrief.intact': 'OPERATIVA',
  'command.debrief.lost': 'PERDIDA',
  'command.debrief.summary': 'Has destruido {n} unidades enemigas: −{troops} tropas enemigas en este frente',
  'command.debrief.none': 'Sin bajas enemigas confirmadas',
  'command.debrief.return': 'Volviendo al mando estratégico…',
  'command.debrief.strategic': 'Unidades estratégicas eliminadas: {n}',
  'command.missileWarning': 'MISIL ENTRANTE',
  'command.incoming': 'IMPACTO ENTRANTE',
  'command.type.tank': 'CARRO',
  'command.type.ifv': 'VCI',
  'command.type.aa': 'ANTIAÉREO',
  'command.type.sam': 'SAM',
  'command.type.truck': 'CAMIÓN',
  'command.type.soldier': 'INFANTERÍA',
  'command.type.at': 'EQUIPO AC',
  'command.type.jet': 'CAZA',
  'command.type.ship': 'FRAGATA',
  'command.type.boat': 'PATRULLERA',
  'command.type.battery': 'BATERÍA COSTERA',
  'command.type.bunker': 'BÚNKER',
  'command.wave': 'Refuerzos enemigos en camino',
  'command.airstrike': 'Ataque aéreo aliado en curso',
};

const en: Record<string, string> = {
  'command.kind.tank': 'Armored division',
  'command.kind.jet': 'Fighter squadron',
  'command.kind.ship': 'Naval group',
  'command.vehicle.tank': 'MAIN BATTLE TANK',
  'command.vehicle.jet': 'MULTIROLE FIGHTER',
  'command.vehicle.ship': 'DESTROYER',
  'command.intro.op': 'OPERATION',
  'command.intro.front': 'Front against {enemy}',
  'command.intro.coords': '{lat} · {lon}',
  'command.intro.local': 'LOCAL TIME {time}',
  'command.objective': 'Destroy {n} enemy units to break the front',
  'command.objective.short': 'BREAK THE FRONT',
  'command.objective.done': 'FRONT BROKEN',
  'command.objective.doneSub': 'The enemy is falling back. Press ESC to return to strategic command',
  'command.hp': 'ARMOR',
  'command.hp.jet': 'AIRFRAME',
  'command.hp.ship': 'HULL',
  'command.ammo.ap': 'AP SHELL',
  'command.ammo.he': 'HE SHELL',
  'command.ammo.mg': 'COAX MG',
  'command.ammo.smoke': 'SMOKE',
  'command.ammo.gun': 'CANNON',
  'command.ammo.aam': 'IR MISSILES',
  'command.ammo.flares': 'FLARES',
  'command.ammo.main': '127 mm GUN',
  'command.ammo.ssm': 'ANTI-SHIP MISSILES',
  'command.ammo.ciws': 'CIWS',
  'command.reload': 'RELOADING',
  'command.ready': 'READY',
  'command.speed': 'SPD',
  'command.alt': 'ALT',
  'command.throttle': 'THR',
  'command.telegraph': 'TELEGRAPH',
  'command.tel.-1': 'ASTERN',
  'command.tel.0': 'STOP',
  'command.tel.1': 'AHEAD 1/3',
  'command.tel.2': 'AHEAD 2/3',
  'command.tel.3': 'AHEAD FULL',
  'command.tel.4': 'FLANK',
  'command.rudder': 'RUDDER',
  'command.range': 'RNG',
  'command.lock': 'LOCKED',
  'command.locking': 'LOCKING',
  'command.missile': 'MISSILE',
  'command.pullUp': 'PULL UP',
  'command.stall': 'LOW SPEED',
  'command.boundary': 'LEAVING THE COMBAT AREA',
  'command.hit': 'HIT',
  'command.kill': 'DESTROYED',
  'command.killF': 'DESTROYED',
  'command.ricochet': 'RICOCHET',
  'command.youKilled': 'You destroyed: {what}',
  'command.feed.you': 'YOU',
  'command.feed.allies': 'ALLIES',
  'command.feed.enemy': 'ENEMY',
  'command.lead': 'LEAD',
  'command.exit': 'RETURN TO COMMAND',
  'command.clickToAim': 'Click to capture the mouse',
  'command.help.tank': 'WASD drive · Mouse aim · Click fire · Right-click sight · 1/2 ammo · Space MG · C smoke · ESC exit',
  'command.help.jet': 'Mouse steer · W/S throttle · A/D roll · Q/E yaw · Click cannon · Right-click missile · F flares · ESC exit',
  'command.help.ship': 'W/S telegraph · A/D rudder · Mouse aim · Click gun · Right-click anti-ship missile · ESC exit',
  'command.destroyed': 'VEHICLE DESTROYED',
  'command.destroyedSub': 'The unit was lost in combat',
  'command.debrief': 'AFTER-ACTION REPORT',
  'command.debrief.kills': 'Enemy units destroyed',
  'command.debrief.troops': 'Enemy casualties on this front',
  'command.debrief.time': 'Duration',
  'command.debrief.acc': 'Accuracy',
  'command.debrief.status': 'Unit status',
  'command.debrief.intact': 'OPERATIONAL',
  'command.debrief.lost': 'LOST',
  'command.debrief.summary': 'You destroyed {n} enemy units: −{troops} enemy troops on this front',
  'command.debrief.none': 'No confirmed enemy casualties',
  'command.debrief.return': 'Returning to strategic command…',
  'command.debrief.strategic': 'Strategic units eliminated: {n}',
  'command.missileWarning': 'MISSILE INBOUND',
  'command.incoming': 'INCOMING',
  'command.type.tank': 'TANK',
  'command.type.ifv': 'IFV',
  'command.type.aa': 'AA GUN',
  'command.type.sam': 'SAM',
  'command.type.truck': 'TRUCK',
  'command.type.soldier': 'INFANTRY',
  'command.type.at': 'AT TEAM',
  'command.type.jet': 'FIGHTER',
  'command.type.ship': 'FRIGATE',
  'command.type.boat': 'PATROL BOAT',
  'command.type.battery': 'COASTAL BATTERY',
  'command.type.bunker': 'BUNKER',
  'command.wave': 'Enemy reinforcements inbound',
  'command.airstrike': 'Friendly air strike inbound',
};

let registered = false;
export function registerCommandStrings(): void {
  if (registered) return;
  registered = true;
  registerDictionary('es', es);
  registerDictionary('en', en);
}
