// FRONT ULTRA — command mode i18n strings (owner: command). Registered once at module load, es + en.

import { registerDictionary } from '../shared/i18n';

const es: Record<string, string> = {
  'command.kind.tank': 'División acorazada',
  'command.kind.jet': 'Escuadrón de caza',
  'command.kind.ship': 'Grupo naval',
  'command.vehicle.tank': 'CARRO DE COMBATE',
  'command.vehicle.jet': 'CAZA POLIVALENTE',
  'command.vehicle.ship': 'DESTRUCTOR',
  'command.intro.coords': '{lat} · {lon}',
  'command.intro.local': 'HORA LOCAL {time}',
  'command.hp': 'BLINDAJE',
  'command.hp.jet': 'INTEGRIDAD',
  'command.hp.ship': 'CASCO',
  'command.ammo.ap': 'PERFORANTE',
  'command.ammo.he': 'EXPLOSIVO',
  'command.ammo.mg': 'AMETRALLADORA',
  'command.ammo.smoke': 'HUMO',
  'command.ammo.gun': 'CAÑÓN',
  'command.ammo.aam': 'MISILES IR',
  'command.ammo.flares': 'BENGALAS',
  'command.ammo.main': 'CAÑÓN 127 mm',
  'command.ammo.ssm': 'MISILES ANTIBUQUE',
  'command.ammo.ciws': 'CIWS',
  'command.reload': 'RECARGANDO',
  'command.ready': 'LISTO',
  'command.speed': 'VEL',
  'command.alt': 'ALT',
  'command.throttle': 'MOTOR',
  'command.telegraph': 'TELÉGRAFO',
  'command.tel.-1': 'ATRÁS',
  'command.tel.0': 'PARADA',
  'command.tel.1': 'AVANTE POCA',
  'command.tel.2': 'AVANTE MEDIA',
  'command.tel.3': 'AVANTE TODA',
  'command.tel.4': 'MÁXIMA',
  'command.rudder': 'TIMÓN',
  'command.range': 'DIST',
  'command.lock': 'FIJADO',
  'command.locking': 'FIJANDO',
  'command.missile': 'MISIL',
  'command.pullUp': 'REMONTA',
  'command.stall': 'VELOCIDAD BAJA',
  'command.hit': 'IMPACTO',
  'command.kill': 'DESTRUIDO',
  'command.killF': 'DESTRUIDA',
  'command.ricochet': 'REBOTE',
  'command.youKilled': 'Has destruido: {what}',
  'command.feed.you': 'TÚ',
  'command.feed.allies': 'ALIADOS',
  'command.feed.enemy': 'ENEMIGO',
  'command.lead': 'AVANCE',
  'command.exit': 'VOLVER AL MANDO',
  'command.clickToAim': 'Haz clic para capturar el ratón',
  'command.destroyed': 'VEHÍCULO DESTRUIDO',
  'command.destroyedSub': 'La unidad se ha perdido en combate',
  'command.debrief': 'INFORME DE COMBATE',
  'command.debrief.kills': 'Unidades enemigas destruidas',
  'command.debrief.time': 'Duración',
  'command.debrief.acc': 'Precisión',
  'command.debrief.status': 'Estado de la unidad',
  'command.debrief.intact': 'OPERATIVA',
  'command.debrief.lost': 'PERDIDA',
  'command.debrief.none': 'Sin bajas enemigas confirmadas',
  'command.debrief.return': 'Volviendo al mando estratégico…',
  'command.missileWarning': 'MISIL ENTRANTE',
  'command.incoming': 'IMPACTO ENTRANTE',
  'command.type.tank': 'CARRO',
  'command.type.ifv': 'VCI',
  'command.type.aa': 'ANTIAÉREO',
  'command.type.sam': 'SAM',
  'command.type.truck': 'CAMIÓN',
  'command.type.soldier': 'INFANTERÍA',
  'command.type.at': 'EQUIPO AC',
  'command.type.jet': 'CAZA',
  'command.type.ship': 'FRAGATA',
  'command.type.boat': 'PATRULLERA',
  'command.type.battery': 'BATERÍA COSTERA',
  'command.type.bunker': 'BÚNKER',
  // --- v2 (W5): command mode inside the real world (DESIGN_V2 §9) ---
  'command.help.tank': 'W/S acelerar y frenar · A/D girar · Ratón torreta · Clic cañón · Clic der. mira · 1/2 munición · Espacio ametralladora · C humo',
  'command.help.jet': 'Ratón dirigir · W/S potencia (Mayús poscombustión) · A/D alabeo · Q/E guiñada · Clic cañón · Clic der. misil · F bengalas',
  'command.help.ship': 'W/S telégrafo · A/D timón · Ratón apuntar · Clic cañón · Clic der. misil antibuque',
  'command.help.common': 'M mapa y destino · + / − tiempo · Tab siguiente vehículo · H ocultar ayuda · Esc volver al mapa',
  'command.help.travel': 'En viaje: A/D girar · W avanzar · S detener · + / − tiempo',
  'command.land.own': 'Territorio propio · en paz',
  'command.land.ownWar': 'Territorio propio · tu país está en guerra',
  'command.land.ownFront': 'Territorio propio · frente con {nation} a {km} km',
  'command.land.allied': '{nation} · aliado',
  'command.land.open': '{nation} · fronteras abiertas',
  'command.land.peace': '{nation} · en paz',
  'command.land.truce': '{nation} · en tregua',
  'command.land.war': '{nation} · en guerra',
  'command.land.incursion': 'INCURSIÓN',
  'command.land.sea': 'Aguas internacionales',
  'command.land.waters': 'Aguas territoriales de {nation} · {state}',
  'command.land.ownWaters': 'Aguas territoriales propias',
  'command.land.airspace': 'Espacio aéreo de {nation} · {state}',
  'command.land.ownAirspace': 'Espacio aéreo propio',
  'command.land.unclaimed': 'Tierra sin dueño',
  'command.state.peace': 'en paz',
  'command.state.truce': 'en tregua',
  'command.state.war': 'en guerra',
  'command.state.allied': 'aliado',
  'command.state.open': 'fronteras abiertas',
  'command.clock.tactical': 'TÁCTICO 1:1',
  'command.clock.travel': 'VIAJE ×{rate} · 1 s = {span}',
  'command.clock.throttled': 'VIAJE ×{rate} (limitado por el terreno)',
  'command.clock.decision': 'DECISIÓN · tiempo detenido',
  'command.clock.tip': 'Tiempo táctico: un segundo real es un segundo de juego y el resto del mundo casi se detiene mientras estás al mando. Sin contacto, + / − comprimen el tiempo para viajar (×10 a ×900); con contacto, al recibir fuego, cerca de una frontera o al llegar vuelve a 1:1.',
  'command.span.s': '{n} s',
  'command.span.min': '{n} min',
  'command.travel.contact': 'Contacto con el enemigo: tiempo real',
  'command.travel.fired': 'Te disparan: tiempo real',
  'command.travel.border': 'Frontera cerca: tiempo real',
  'command.travel.arrived': 'Has llegado al destino',
  'command.travel.alert': 'Alerta importante: tiempo real',
  'command.travel.noContact': 'Solo puedes comprimir el tiempo sin contacto con el enemigo',
  'command.travel.needWaypoint': '×300 y ×900 necesitan un destino: pulsa M y haz clic en el mapa',
  'command.travel.foreignMax': 'En territorio ajeno el máximo es ×60',
  'command.travel.manualMax': 'Conduciendo a mano el máximo es ×60; fija un destino con M para ir más rápido',
  'command.travel.column': 'Marcha en columna a {kmh} km/h: la velocidad estratégica de la unidad',
  'command.travel.eta': 'Destino a {km} km · {time} de juego',
  'command.travel.autopilot': 'PILOTO AUTOMÁTICO',
  'command.travel.manual': 'Mando manual: piloto automático desconectado',
  'command.border.approach': 'Frontera con {nation} ({state}) a {km} km',
  'command.border.enterFree': 'Entras en {nation} ({state}): no es una incursión',
  'command.border.left': 'Has salido de {nation}',
  'command.incursion.title': 'Cruzar la frontera de {nation}',
  'command.incursion.body': 'Entrar en {nation} sin permiso es una incursión. {nation} recibirá una alerta y podrá protestar, enviar fuerzas o declararte la guerra.',
  'command.incursion.bodyWater': 'Entrar en las aguas territoriales de {nation} sin permiso es una incursión. {nation} recibirá una alerta y podrá protestar, enviar fuerzas o declararte la guerra.',
  'command.incursion.bodyAir': 'Entrar en el espacio aéreo de {nation} sin permiso es una incursión. {nation} recibirá una alerta y podrá protestar, enviar cazas o declararte la guerra.',
  'command.incursion.cross': 'Cruzar',
  'command.incursion.back': 'Volver',
  'command.incursion.active': '{nation} ha detectado tu incursión y decidirá cómo responder.',
  'command.incursion.protest': '{nation} protesta y exige que te retires antes de {h} h.',
  'command.incursion.intercept': 'Una fuerza de reacción de {nation} viene hacia ti: llega en {min} min.',
  'command.incursion.escort': 'La fuerza de reacción de {nation} te escolta: bloquea y vigila, no dispara mientras sigáis en paz.',
  'command.incursion.war': '{nation} te ha declarado la guerra por la incursión.',
  'command.fire.title': 'Abrir fuego contra {nation}',
  'command.fire.body': 'Estás en paz con {nation}. Disparar primero es una declaración de guerra por tu parte, con todas sus consecuencias: sus aliados pueden entrar en la guerra y el resto del mundo lo recordará.',
  'command.fire.declare': 'Declarar la guerra',
  'command.fire.hold': 'No disparar',
  'command.fire.declared': 'Has declarado la guerra a {nation}',
  'command.exit.title': '¿Volver al mapa estratégico?',
  'command.exit.body': 'La unidad se queda donde la dejas. Todo lo que ha pasado aquí ya está aplicado en la simulación.',
  'command.exit.foreign': 'Estás dentro de {nation}: al salir, la unidad volverá sola a tu territorio y la incursión durará hasta que salga.',
  'command.exit.yes': 'Volver al mapa',
  'command.exit.no': 'Seguir al mando',
  'command.debrief2.title': 'INFORME',
  'command.debrief2.distance': 'Distancia recorrida',
  'command.debrief2.gameTime': 'Tiempo de juego',
  'command.debrief2.kills': 'Enemigos destruidos',
  'command.debrief2.equiv': 'Equivalente estratégico',
  'command.debrief2.troops': '−{troops} tropas de {nation}',
  'command.debrief2.hits': 'Daño a unidades reales',
  'command.debrief2.hitsV': '{n} impactos · {pct} % de integridad',
  'command.debrief2.structs': 'Daño a estructuras',
  'command.debrief2.losses': 'Pérdidas propias',
  'command.debrief2.lossesV': '{n} vehículos · la unidad queda al {pct} %',
  'command.debrief2.noLosses': 'Ninguna',
  'command.debrief2.synced': 'Todo esto ya está aplicado en la simulación.',
  'command.debrief2.none': 'Sin combates',
  'command.debrief2.lost': 'La unidad ha sido destruida',
  'command.debrief2.return': 'Volviendo al mapa estratégico…',
  'command.title.line': '{place} · {land}',
  'command.formation.tank': '{n} carros',
  'command.formation.jet': '{n} cazas',
  'command.formation.ship': 'buque',
  'command.formation.integrity': 'Integridad {pct} %',
  'command.next.tank': 'Tu carro ha sido destruido. Tomas el siguiente en {s} s (Tab)',
  'command.next.jet': 'Tu caza ha sido derribado. Tomas el siguiente en {s} s (Tab)',
  'command.map.title': 'MAPA TÁCTICO · {km} km',
  'command.map.hint': 'Clic: fijar destino · clic derecho: borrar destino · M: cerrar',
  'command.map.you': 'Tu unidad',
  'command.map.waypoint': 'Destino',
  'command.map.town': 'Ciudad',
  'command.map.border': 'Frontera',
  'command.map.front': 'Frente',
  'command.map.enemy': 'Enemigo',
  'command.map.friendly': 'Propio',
  'command.map.neutral': 'En paz',
  'command.label.capital': 'Capital',
  'command.label.border': 'Frontera · {nation}',
  'command.label.cityLevel': 'Ciudad · nivel {n}',
  'command.label.baseAt': '{type} de {place}',
  'command.label.level': 'Nivel {n}',
  'command.town.near': 'Ciudad cerca de {place}',
  'command.town.unnamed': 'Ciudad',
  'command.src.division': '{unit} de {nation} · {pct} %',
  'command.src.formation': 'Tu formación · {unit}',
  'command.src.qrf': 'Fuerza de reacción de {nation}',
  'command.src.sam': 'SAM de {nation}',
  'command.src.post': 'Puesto defensivo de {nation}',
  'command.src.ship': '{unit} de {nation} · {pct} %',
  'command.src.squadron': '{unit} de {nation}',
  'command.alerts.back': 'Esc: volver al mapa',
  'command.peace.notice': 'Aquí no hay combates: estás en tu territorio y en paz. Conduce libremente; + / − comprimen el tiempo en los viajes y M abre el mapa.',
  'command.loading': 'Cargando el terreno real…',
  'alert.incursion.protest.title': '{nation} protesta por tu incursión',
  'alert.incursion.protest.body': '{nation} protesta por la entrada de tu {unit} y exige su retirada en 6 h. Si no sales, podría enviar fuerzas.',
  'alert.incursion.intercept.title': '{nation} envía una fuerza de reacción',
  'alert.incursion.intercept.body': 'Una fuerza de reacción rápida de {nation} sale hacia tu {unit} y llegará en unos {min} min. Bloqueará y escoltará, sin disparar mientras sigáis en paz.',
  'alert.incursion.war.title': '{nation} te declara la guerra',
  'alert.incursion.war.body': 'La incursión de tu {unit} en su territorio ha llevado a {nation} a declararte la guerra.',
  'alert.incursion.escalated': 'Ignoraste su protesta.',
  'alert.incursion.arrived.title': 'La fuerza de reacción de {nation} ha llegado',
  'alert.incursion.arrived.body': 'Escolta a tu {unit}. No disparará mientras sigáis en paz; si disparas tú, será la guerra.',
  'alert.incursion.entered.title': 'Incursión en {nation}',
  'alert.incursion.entered.body': 'Tu {unit} ha entrado en {nation} sin permiso. {nation} decidirá cómo responder.',
};

const en: Record<string, string> = {
  'command.kind.tank': 'Armored division',
  'command.kind.jet': 'Fighter squadron',
  'command.kind.ship': 'Naval group',
  'command.vehicle.tank': 'MAIN BATTLE TANK',
  'command.vehicle.jet': 'MULTIROLE FIGHTER',
  'command.vehicle.ship': 'DESTROYER',
  'command.intro.coords': '{lat} · {lon}',
  'command.intro.local': 'LOCAL TIME {time}',
  'command.hp': 'ARMOR',
  'command.hp.jet': 'AIRFRAME',
  'command.hp.ship': 'HULL',
  'command.ammo.ap': 'AP SHELL',
  'command.ammo.he': 'HE SHELL',
  'command.ammo.mg': 'COAX MG',
  'command.ammo.smoke': 'SMOKE',
  'command.ammo.gun': 'CANNON',
  'command.ammo.aam': 'IR MISSILES',
  'command.ammo.flares': 'FLARES',
  'command.ammo.main': '127 mm GUN',
  'command.ammo.ssm': 'ANTI-SHIP MISSILES',
  'command.ammo.ciws': 'CIWS',
  'command.reload': 'RELOADING',
  'command.ready': 'READY',
  'command.speed': 'SPD',
  'command.alt': 'ALT',
  'command.throttle': 'THR',
  'command.telegraph': 'TELEGRAPH',
  'command.tel.-1': 'ASTERN',
  'command.tel.0': 'STOP',
  'command.tel.1': 'AHEAD 1/3',
  'command.tel.2': 'AHEAD 2/3',
  'command.tel.3': 'AHEAD FULL',
  'command.tel.4': 'FLANK',
  'command.rudder': 'RUDDER',
  'command.range': 'RNG',
  'command.lock': 'LOCKED',
  'command.locking': 'LOCKING',
  'command.missile': 'MISSILE',
  'command.pullUp': 'PULL UP',
  'command.stall': 'LOW SPEED',
  'command.hit': 'HIT',
  'command.kill': 'DESTROYED',
  'command.killF': 'DESTROYED',
  'command.ricochet': 'RICOCHET',
  'command.youKilled': 'You destroyed: {what}',
  'command.feed.you': 'YOU',
  'command.feed.allies': 'ALLIES',
  'command.feed.enemy': 'ENEMY',
  'command.lead': 'LEAD',
  'command.exit': 'RETURN TO COMMAND',
  'command.clickToAim': 'Click to capture the mouse',
  'command.destroyed': 'VEHICLE DESTROYED',
  'command.destroyedSub': 'The unit was lost in combat',
  'command.debrief': 'AFTER-ACTION REPORT',
  'command.debrief.kills': 'Enemy units destroyed',
  'command.debrief.time': 'Duration',
  'command.debrief.acc': 'Accuracy',
  'command.debrief.status': 'Unit status',
  'command.debrief.intact': 'OPERATIONAL',
  'command.debrief.lost': 'LOST',
  'command.debrief.none': 'No confirmed enemy casualties',
  'command.debrief.return': 'Returning to strategic command…',
  'command.missileWarning': 'MISSILE INBOUND',
  'command.incoming': 'INCOMING',
  'command.type.tank': 'TANK',
  'command.type.ifv': 'IFV',
  'command.type.aa': 'AA GUN',
  'command.type.sam': 'SAM',
  'command.type.truck': 'TRUCK',
  'command.type.soldier': 'INFANTRY',
  'command.type.at': 'AT TEAM',
  'command.type.jet': 'FIGHTER',
  'command.type.ship': 'FRIGATE',
  'command.type.boat': 'PATROL BOAT',
  'command.type.battery': 'COASTAL BATTERY',
  'command.type.bunker': 'BUNKER',
  // --- v2 (W5): command mode inside the real world (DESIGN_V2 §9) ---
  'command.help.tank': 'W/S throttle and brake · A/D steer · Mouse turret · Click cannon · Right-click sight · 1/2 ammo · Space MG · C smoke',
  'command.help.jet': 'Mouse steer · W/S throttle (Shift afterburner) · A/D roll · Q/E yaw · Click cannon · Right-click missile · F flares',
  'command.help.ship': 'W/S telegraph · A/D rudder · Mouse aim · Click gun · Right-click anti-ship missile',
  'command.help.common': 'M map and waypoint · + / − time · Tab next vehicle · H hide help · Esc back to the map',
  'command.help.travel': 'Travelling: A/D turn · W go · S stop · + / − time',
  'command.land.own': 'Own territory · at peace',
  'command.land.ownWar': 'Own territory · your country is at war',
  'command.land.ownFront': 'Own territory · front with {nation} {km} km away',
  'command.land.allied': '{nation} · ally',
  'command.land.open': '{nation} · open borders',
  'command.land.peace': '{nation} · at peace',
  'command.land.truce': '{nation} · truce',
  'command.land.war': '{nation} · at war',
  'command.land.incursion': 'INCURSION',
  'command.land.sea': 'International waters',
  'command.land.waters': 'Territorial waters of {nation} · {state}',
  'command.land.ownWaters': 'Own territorial waters',
  'command.land.airspace': 'Airspace of {nation} · {state}',
  'command.land.ownAirspace': 'Own airspace',
  'command.land.unclaimed': 'Unclaimed land',
  'command.state.peace': 'at peace',
  'command.state.truce': 'truce',
  'command.state.war': 'at war',
  'command.state.allied': 'ally',
  'command.state.open': 'open borders',
  'command.clock.tactical': 'TACTICAL 1:1',
  'command.clock.travel': 'TRAVEL ×{rate} · 1 s = {span}',
  'command.clock.throttled': 'TRAVEL ×{rate} (limited by the terrain)',
  'command.clock.decision': 'DECISION · time stopped',
  'command.clock.tip': 'Tactical time: one real second is one game second, and the rest of the world almost stops while you are in command. Without contact, + / − compress time to travel (×10 to ×900); contact, incoming fire, a nearby border or arriving bring it back to 1:1.',
  'command.span.s': '{n} s',
  'command.span.min': '{n} min',
  'command.travel.contact': 'Enemy contact: real time',
  'command.travel.fired': 'Under fire: real time',
  'command.travel.border': 'Border ahead: real time',
  'command.travel.arrived': 'You have arrived',
  'command.travel.alert': 'Important alert: real time',
  'command.travel.noContact': 'Time can only be compressed without enemy contact',
  'command.travel.needWaypoint': '×300 and ×900 need a destination: press M and click on the map',
  'command.travel.foreignMax': 'In foreign land the maximum is ×60',
  'command.travel.manualMax': 'Driving by hand the maximum is ×60; set a destination with M to go faster',
  'command.travel.column': 'Column march at {kmh} km/h: the unit\'s strategic speed',
  'command.travel.eta': 'Destination {km} km away · {time} of game time',
  'command.travel.autopilot': 'AUTOPILOT',
  'command.travel.manual': 'Manual control: autopilot off',
  'command.border.approach': 'Border with {nation} ({state}) {km} km ahead',
  'command.border.enterFree': 'Entering {nation} ({state}): not an incursion',
  'command.border.left': 'You have left {nation}',
  'command.incursion.title': 'Cross the border of {nation}',
  'command.incursion.body': 'Entering {nation} without permission is an incursion. {nation} will be alerted and may protest, send forces or declare war on you.',
  'command.incursion.bodyWater': 'Entering the territorial waters of {nation} without permission is an incursion. {nation} will be alerted and may protest, send forces or declare war on you.',
  'command.incursion.bodyAir': 'Entering the airspace of {nation} without permission is an incursion. {nation} will be alerted and may protest, scramble fighters or declare war on you.',
  'command.incursion.cross': 'Cross',
  'command.incursion.back': 'Go back',
  'command.incursion.active': '{nation} has detected your incursion and will decide how to respond.',
  'command.incursion.protest': '{nation} protests and demands you withdraw within {h} h.',
  'command.incursion.intercept': 'A quick-reaction force of {nation} is coming for you: arrives in {min} min.',
  'command.incursion.escort': 'The quick-reaction force of {nation} is escorting you: it blocks and watches, and will not fire while you are at peace.',
  'command.incursion.war': '{nation} has declared war on you over the incursion.',
  'command.fire.title': 'Open fire on {nation}',
  'command.fire.body': 'You are at peace with {nation}. Firing first is a declaration of war by you, with all its consequences: its allies may join the war and the rest of the world will remember.',
  'command.fire.declare': 'Declare war',
  'command.fire.hold': 'Hold fire',
  'command.fire.declared': 'You declared war on {nation}',
  'command.exit.title': 'Return to the strategic map?',
  'command.exit.body': 'The unit stays where you leave it. Everything that happened here is already applied to the simulation.',
  'command.exit.foreign': 'You are inside {nation}: on leaving, the unit will drive back to your territory by itself and the incursion lasts until it is out.',
  'command.exit.yes': 'Back to the map',
  'command.exit.no': 'Stay in command',
  'command.debrief2.title': 'REPORT',
  'command.debrief2.distance': 'Distance travelled',
  'command.debrief2.gameTime': 'Game time',
  'command.debrief2.kills': 'Enemies destroyed',
  'command.debrief2.equiv': 'Strategic equivalent',
  'command.debrief2.troops': '−{troops} troops of {nation}',
  'command.debrief2.hits': 'Damage to real units',
  'command.debrief2.hitsV': '{n} hits · {pct} % of integrity',
  'command.debrief2.structs': 'Damage to structures',
  'command.debrief2.losses': 'Own losses',
  'command.debrief2.lossesV': '{n} vehicles · the unit is at {pct} %',
  'command.debrief2.noLosses': 'None',
  'command.debrief2.synced': 'All of this is already applied to the simulation.',
  'command.debrief2.none': 'No fighting',
  'command.debrief2.lost': 'The unit was destroyed',
  'command.debrief2.return': 'Returning to the strategic map…',
  'command.title.line': '{place} · {land}',
  'command.formation.tank': '{n} tanks',
  'command.formation.jet': '{n} fighters',
  'command.formation.ship': 'ship',
  'command.formation.integrity': 'Integrity {pct} %',
  'command.next.tank': 'Your tank was destroyed. You take the next one in {s} s (Tab)',
  'command.next.jet': 'Your fighter was shot down. You take the next one in {s} s (Tab)',
  'command.map.title': 'TACTICAL MAP · {km} km',
  'command.map.hint': 'Click: set destination · right-click: clear destination · M: close',
  'command.map.you': 'Your unit',
  'command.map.waypoint': 'Destination',
  'command.map.town': 'Town',
  'command.map.border': 'Border',
  'command.map.front': 'Front',
  'command.map.enemy': 'Enemy',
  'command.map.friendly': 'Own',
  'command.map.neutral': 'At peace',
  'command.label.border': 'Border · {nation}',
  'command.label.capital': 'Capital',
  'command.label.cityLevel': 'City · level {n}',
  'command.label.baseAt': '{type} at {place}',
  'command.label.level': 'Level {n}',
  'command.town.near': 'City near {place}',
  'command.town.unnamed': 'City',
  'command.src.division': '{unit} of {nation} · {pct} %',
  'command.src.formation': 'Your formation · {unit}',
  'command.src.qrf': 'Quick-reaction force of {nation}',
  'command.src.sam': 'SAM of {nation}',
  'command.src.post': 'Defense post of {nation}',
  'command.src.ship': '{unit} of {nation} · {pct} %',
  'command.src.squadron': '{unit} of {nation}',
  'command.alerts.back': 'Esc: back to the map',
  'command.peace.notice': 'No fighting here: you are in your own territory, at peace. Drive freely; + / − compress time for travel and M opens the map.',
  'command.loading': 'Loading the real terrain…',
  'alert.incursion.protest.title': '{nation} protests against your incursion',
  'alert.incursion.protest.body': '{nation} protests against the entry of your {unit} and demands its withdrawal within 6 h. If you stay, it may send forces.',
  'alert.incursion.intercept.title': '{nation} sends a quick-reaction force',
  'alert.incursion.intercept.body': 'A quick-reaction force of {nation} is heading for your {unit} and will arrive in about {min} min. It will block and escort, without firing while you are at peace.',
  'alert.incursion.war.title': '{nation} declares war on you',
  'alert.incursion.war.body': 'The incursion of your {unit} into its territory has led {nation} to declare war on you.',
  'alert.incursion.escalated': 'You ignored its protest.',
  'alert.incursion.arrived.title': 'The quick-reaction force of {nation} has arrived',
  'alert.incursion.arrived.body': 'It is escorting your {unit}. It will not fire while you are at peace; if you fire, it is war.',
  'alert.incursion.entered.title': 'Incursion into {nation}',
  'alert.incursion.entered.body': 'Your {unit} entered {nation} without permission. {nation} will decide how to respond.',
};

/** The dictionaries (tools/i18n-check.mjs reads them). */
export const COMMAND_STRINGS = { es, en };

let registered = false;
export function registerCommandStrings(): void {
  if (registered) return;
  registered = true;
  registerDictionary('es', es);
  registerDictionary('en', en);
}
