// FRONT ULTRA — command mode i18n strings (owner: command). Registered once at module load, es + en.

import { registerDictionary } from '../shared/i18n';

const es: Record<string, string> = {
  'command.kind.tank': 'División acorazada',
  'command.kind.jet': 'Escuadrón de caza',
  'command.kind.ship': 'Grupo naval',
  'command.vehicle.tank': 'CARRO DE COMBATE',
  'command.vehicle.jet': 'CAZA POLIVALENTE',
  'command.vehicle.ship': 'DESTRUCTOR',
  'command.intro.coords': '{lat} · {lon}',
  'command.intro.local': 'HORA LOCAL {time}',
  'command.hp': 'BLINDAJE',
  'command.hp.jet': 'INTEGRIDAD',
  'command.hp.ship': 'CASCO',
  'command.ammo.ap': 'PERFORANTE',
  'command.ammo.he': 'EXPLOSIVO',
  'command.ammo.mg': 'AMETRALLADORA',
  'command.ammo.smoke': 'HUMO',
  'command.ammo.gun': 'CAÑÓN',
  'command.ammo.aam': 'MISILES IR',
  'command.ammo.flares': 'BENGALAS',
  'command.ammo.main': 'CAÑÓN 127 mm',
  'command.ammo.ssm': 'MISILES ANTIBUQUE',
  'command.ammo.ciws': 'CIWS',
  'command.reload': 'RECARGANDO',
  'command.ready': 'LISTO',
  'command.speed': 'VEL',
  'command.alt': 'ALT',
  'command.throttle': 'MOTOR',
  'command.telegraph': 'TELÉGRAFO',
  'command.tel.-1': 'ATRÁS',
  'command.tel.0': 'PARADA',
  'command.tel.1': 'AVANTE POCA',
  'command.tel.2': 'AVANTE MEDIA',
  'command.tel.3': 'AVANTE TODA',
  'command.tel.4': 'MÁXIMA',
  'command.rudder': 'TIMÓN',
  'command.range': 'DIST',
  'command.lock': 'FIJADO',
  'command.locking': 'FIJANDO',
  'command.missile': 'MISIL',
  'command.pullUp': 'REMONTA',
  'command.stall': 'VELOCIDAD BAJA',
  'command.hit': 'IMPACTO',
  'command.kill': 'DESTRUIDO',
  'command.killF': 'DESTRUIDA',
  'command.ricochet': 'REBOTE',
  'command.youKilled': 'Has destruido: {what}',
  'command.feed.you': 'TÚ',
  'command.feed.allies': 'ALIADOS',
  'command.feed.enemy': 'ENEMIGO',
  'command.lead': 'AVANCE',
  'command.exit': 'VOLVER AL MANDO',
  'command.clickToAim': 'Haz clic para capturar el ratón',
  'command.destroyed': 'VEHÍCULO DESTRUIDO',
  'command.destroyedSub': 'La unidad se ha perdido en combate',
  'command.debrief': 'INFORME DE COMBATE',
  'command.debrief.kills': 'Unidades enemigas destruidas',
  'command.debrief.time': 'Duración',
  'command.debrief.acc': 'Precisión',
  'command.debrief.status': 'Estado de la unidad',
  'command.debrief.intact': 'OPERATIVA',
  'command.debrief.lost': 'PERDIDA',
  'command.debrief.none': 'Sin bajas enemigas confirmadas',
  'command.debrief.return': 'Volviendo al mando estratégico…',
  'command.missileWarning': 'MISIL ENTRANTE',
  'command.incoming': 'IMPACTO ENTRANTE',
  'command.type.tank': 'CARRO',
  'command.type.ifv': 'VCI',
  'command.type.aa': 'ANTIAÉREO',
  'command.type.sam': 'SAM',
  'command.type.truck': 'CAMIÓN',
  'command.type.soldier': 'INFANTERÍA',
  'command.type.at': 'EQUIPO AC',
  'command.type.jet': 'CAZA',
  'command.type.ship': 'FRAGATA',
  'command.type.boat': 'PATRULLERA',
  'command.type.battery': 'BATERÍA COSTERA',
  'command.type.bunker': 'BÚNKER',
  // --- v2 (W5): command mode inside the real world (DESIGN_V2 §9) ---
  'command.help.tank': 'W/S acelerar y frenar · A/D girar · Ratón torreta · Clic cañón · Clic der. mira · 1/2 munición · Espacio ametralladora · C humo',
  'command.help.jet': 'Ratón dirigir · W/S potencia (Mayús poscombustión) · A/D alabeo · Q/E guiñada · Clic cañón · Clic der. misil · F bengalas',
  'command.help.ship': 'W/S telégrafo · A/D timón · Ratón apuntar · Clic cañón · Clic der. misil antibuque',
  'command.help.common': 'M mapa y destino · + / − tiempo · Tab siguiente vehículo · H ocultar ayuda · Esc volver al mapa',
  'command.help.travel': 'En viaje: A/D girar · W avanzar · S detener · + / − tiempo',
  'command.land.own': 'Territorio propio · en paz',
  'command.land.ownWar': 'Territorio propio · tu país está en guerra',
  'command.land.ownFront': 'Territorio propio · línea del frente con {nation} a {km} km',
  'command.land.ownBattle': 'Territorio propio · combate con {nation} a {km} km',
  'command.land.allied': '{nation} · aliado',
  'command.land.open': '{nation} · fronteras abiertas',
  'command.land.peace': '{nation} · en paz',
  'command.land.truce': '{nation} · en tregua',
  'command.land.war': '{nation} · en guerra',
  'command.land.incursion': 'INCURSIÓN',
  'command.land.sea': 'Aguas internacionales',
  'command.land.waters': 'Aguas territoriales de {nation} · {state}',
  'command.land.ownWaters': 'Aguas territoriales propias',
  'command.land.airspace': 'Espacio aéreo de {nation} · {state}',
  'command.land.ownAirspace': 'Espacio aéreo propio',
  'command.land.unclaimed': 'Tierra sin dueño',
  'command.state.peace': 'en paz',
  'command.state.truce': 'en tregua',
  'command.state.war': 'en guerra',
  'command.state.allied': 'aliado',
  'command.state.open': 'fronteras abiertas',
  'command.clock.tactical': 'TÁCTICO 1:1',
  'command.clock.travel': 'VIAJE ×{rate} · 1 s = {span}',
  'command.clock.throttled': 'VIAJE ×{rate} (limitado por el terreno)',
  'command.clock.decision': 'DECISIÓN · tiempo detenido',
  'command.clock.tip': 'Tiempo táctico: un segundo real es un segundo de juego y el resto del mundo casi se detiene mientras estás al mando. Sin contacto, + / − comprimen el tiempo para viajar (×10 a ×900); con contacto, al recibir fuego, cerca de una frontera o al llegar vuelve a 1:1.',
  'command.span.s': '{n} s',
  'command.span.min': '{n} min',
  'command.travel.contact': 'Contacto con el enemigo: tiempo real',
  'command.travel.fired': 'Te disparan: tiempo real',
  'command.travel.border': 'Frontera cerca: tiempo real',
  'command.travel.arrived': 'Has llegado al destino',
  'command.travel.alert': 'Alerta importante: tiempo real',
  'command.travel.noContact': 'Solo puedes comprimir el tiempo sin contacto con el enemigo',
  'command.travel.needWaypoint': '×300 y ×900 necesitan un destino: pulsa M y haz clic en el mapa',
  'command.travel.foreignMax': 'En territorio ajeno el máximo es ×60',
  'command.travel.manualMax': 'Conduciendo a mano el máximo es ×60; fija un destino con M para ir más rápido',
  'command.travel.column': 'Marcha en columna a {kmh} km/h: la velocidad estratégica de la unidad',
  'command.travel.eta': 'Destino a {km} km · {time} de juego',
  'command.travel.autopilot': 'PILOTO AUTOMÁTICO',
  'command.travel.manual': 'Mando manual: piloto automático desconectado',
  'command.border.approach': 'Frontera con {nation} ({state}) a {km} km',
  'command.border.enterFree': 'Entras en {nation} ({state}): no es una incursión',
  'command.border.left': 'Has salido de {nation}',
  'command.incursion.title': 'Cruzar la frontera de {nation}',
  'command.incursion.body': 'Entrar en {nation} sin permiso es una incursión. {nation} recibirá una alerta y podrá protestar, enviar fuerzas o declararte la guerra.',
  'command.incursion.bodyWater': 'Entrar en las aguas territoriales de {nation} sin permiso es una incursión. {nation} recibirá una alerta y podrá protestar, enviar fuerzas o declararte la guerra.',
  'command.incursion.bodyAir': 'Entrar en el espacio aéreo de {nation} sin permiso es una incursión. {nation} recibirá una alerta y podrá protestar, enviar cazas o declararte la guerra.',
  'command.incursion.cross': 'Cruzar',
  'command.incursion.back': 'Volver',
  'command.fire.title': 'Abrir fuego contra {nation}',
  'command.fire.body': 'Estás en paz con {nation}. Disparar primero es una declaración de guerra por tu parte, con todas sus consecuencias: sus aliados pueden entrar en la guerra y el resto del mundo lo recordará.',
  'command.fire.declare': 'Declarar la guerra',
  'command.fire.hold': 'No disparar',
  'command.fire.declared': 'Has declarado la guerra a {nation}',
  'command.exit.title': '¿Volver al mapa estratégico?',
  'command.exit.body': 'La unidad se queda donde la dejas. Todo lo que ha pasado aquí ya está aplicado en la simulación.',
  'command.exit.yes': 'Volver al mapa',
  'command.exit.no': 'Seguir al mando',
  'command.debrief2.title': 'INFORME',
  'command.debrief2.distance': 'Distancia recorrida',
  'command.debrief2.gameTime': 'Tiempo de juego',
  'command.debrief2.kills': 'Enemigos destruidos',
  'command.debrief2.equiv': 'Equivalente estratégico',
  'command.debrief2.troops': '−{troops} tropas de {nation}',
  'command.debrief2.hits': 'Daño a unidades reales',
  'command.debrief2.hitsV': '{n} impactos · {pct} % de integridad',
  'command.debrief2.structs': 'Daño a estructuras',
  'command.debrief2.losses': 'Pérdidas propias',
  'command.debrief2.lossesV': '{n} vehículos · la unidad queda al {pct} %',
  'command.debrief2.noLosses': 'Ninguna',
  'command.debrief2.synced': 'Todo esto ya está aplicado en la simulación.',
  'command.debrief2.none': 'Sin combates',
  'command.debrief2.lost': 'La unidad ha sido destruida',
  'command.debrief2.return': 'Volviendo al mapa estratégico…',
  'command.title.line': '{place} · {land}',
  'command.formation.tank': '{n} carros',
  'command.formation.jet': '{n} cazas',
  'command.formation.ship': 'buque',
  'command.formation.integrity': 'Integridad {pct} %',
  'command.next.tank': 'Tu carro ha sido destruido. Tomas el siguiente en {s} s (Tab)',
  'command.next.jet': 'Tu caza ha sido derribado. Tomas el siguiente en {s} s (Tab)',
  'command.map.title': 'MAPA TÁCTICO · {km} km',
  'command.map.hint': 'Clic: fijar destino · clic derecho: borrar destino · M: cerrar',
  'command.map.you': 'Tu unidad',
  'command.map.waypoint': 'Destino',
  'command.map.town': 'Ciudad',
  'command.map.border': 'Frontera',
  'command.map.front': 'Frente',
  'command.map.enemy': 'Enemigo',
  'command.map.friendly': 'Propio',
  'command.map.neutral': 'En paz',
  'command.label.capital': 'Capital',
  'command.label.border': 'Frontera · {nation}',
  'command.label.battle': 'Combate · {a} contra {b}',
  'command.label.battleSub': '{n} soldados en la línea',
  'command.battle.there': 'La batalla que mirabas está a {km} km al {dir} (distancia a su centro): sus {n} soldados siguen allí, donde los viste. Tienes el destino marcado en ella: síguelo hasta la etiqueta «Combate».',
  'command.battle.here': 'Estás en la batalla que mirabas: sus {n} soldados siguen donde los viste.',
  'command.label.cityLevel': 'Ciudad · nivel {n}',
  'command.label.baseAt': '{type} de {place}',
  'command.label.level': 'Nivel {n}',
  'command.town.near': 'Ciudad cerca de {place}',
  'command.town.unnamed': 'Ciudad',
  'command.src.division': '{unit} de {nation} · {pct} %',
  'command.src.formation': 'Tu formación · {unit}',
  'command.src.qrf': 'Fuerza de reacción de {nation}',
  'command.src.sam': 'SAM de {nation}',
  'command.src.post': 'Puesto defensivo de {nation}',
  'command.src.ship': '{unit} de {nation} · {pct} %',
  'command.src.squadron': '{unit} de {nation}',
  'command.alerts.back': 'Esc: volver al mapa',
  'command.peace.notice': 'Aquí no hay combates: estás en tu territorio y en paz. Conduce libremente; + / − comprimen el tiempo en los viajes y M abre el mapa.',
  'command.loading': 'Cargando el terreno real…',

  // Incursions (owner feedback #18-#20): the radio warning with its countdown, the interception, the last warning.
  'command.exit.foreign': 'Estás dentro de {nation}: la unidad se quedará aquí, sin volver sola, y la incursión seguirá: {nation} seguirá reaccionando hasta que salgas.',
  'command.exit.bodyJet': 'El escuadrón se queda en espera sobre este punto, dando vueltas a 12 km de él, durante 12 horas de juego (relevando aviones con su base; su ficha muestra cuánto le queda); después vuelve a su base a repostar. Puedes darle otra orden cuando quieras. Todo lo que ha pasado aquí ya está aplicado en la simulación.',
  'command.dur.s': '{n} s',
  'command.dur.min': '{n} min',
  'command.dur.ms': '{m} min {s} s',
  'command.dir.0': 'norte', 'command.dir.1': 'noreste', 'command.dir.2': 'este', 'command.dir.3': 'sureste',
  'command.dir.4': 'sur', 'command.dir.5': 'suroeste', 'command.dir.6': 'oeste', 'command.dir.7': 'noroeste',
  'command.radio.tag': 'RADIO',
  'command.radio.from.jet': 'Control aéreo de {nation}',
  'command.radio.from.tank': 'Mando fronterizo de {nation}',
  'command.radio.from.ship': 'Guardacostas de {nation}',
  'command.radio.warn.jet': '«Aeronave no autorizada: estás violando el espacio aéreo de {nation}. Vira y abandónalo de inmediato o serás interceptada.»',
  'command.radio.warn.tank': '«Unidad armada: has entrado en {nation} sin autorización. Da la vuelta ahora o enviaremos fuerzas a detenerte.»',
  'command.radio.warn.ship': '«Buque de guerra: estás en aguas territoriales de {nation} sin autorización. Cambia el rumbo y sal o serás interceptado.»',
  'command.radio.capital': 'Estás cerca de su capital: no habrá más avisos.',
  'command.radio.count.grace': 'Para dar la vuelta',
  'command.radio.intercept.air': 'Cazas de {nation} despegados desde {source}. Te alcanzan en {t}: sal de su espacio aéreo antes.',
  'command.radio.intercept.tank': '{what} de {nation} sale de {source} hacia ti. Llega en {t}: sal de su territorio antes.',
  'command.radio.intercept.ship': '{what} de {nation} navega hacia ti desde {source}. Llega en {t}: sal de sus aguas antes.',
  'command.radio.count.eta': 'Llegada de la interceptación',
  'command.radio.escort.air': '«Aquí los cazas de {nation}, a tu costado. Síguenos fuera de nuestro espacio aéreo. Si no sales, abriremos fuego.»',
  'command.radio.escort.tank': '«Aquí la patrulla de {nation}: no sigas avanzando. Vuelve a la frontera escoltado o abriremos fuego.»',
  'command.radio.escort.ship': '«Aquí {nation}: te seguimos de cerca. Pon rumbo fuera de nuestras aguas o abriremos fuego.»',
  'command.radio.closing.air': '«Cazas de {nation} a {d} de ti, uniéndonos a tu costado. Da la vuelta: sal de nuestro espacio aéreo o abriremos fuego.»',
  'command.radio.closing.tank': '«Patrulla de {nation}, a {d} de ti y acercándonos. Detente y vuelve a la frontera o abriremos fuego.»',
  'command.radio.closing.ship': '«Aquí {nation}, a {d} de ti y acercándonos. Pon rumbo fuera de nuestras aguas o abriremos fuego.»',
  'command.radio.count.last': 'Último aviso',
  'command.radio.engage': '{nation} ha abierto fuego contra ti. Sal de su territorio: responder al fuego es defenderse, pero si sigues dentro acabará en guerra.',
  'command.radio.war': '{nation} te ha declarado la guerra por la incursión: sus fuerzas son enemigas.',
  'command.radio.protest': '{nation} no tiene con qué interceptarte, pero protesta y exige que salgas.',
  'command.radio.count.protest': 'Plazo de su protesta',
  'command.radio.exit': 'Salida más cercana: {km} km al {dir}',
  'command.radio.nofire': 'No dispararán mientras sigáis en paz; si disparas tú, será la guerra.',
  'command.qrf.src.city': 'la guarnición de una ciudad a {km} km',
  'command.qrf.src.post': 'un puesto defensivo a {km} km',
  'command.qrf.src.base': 'una base del ejército a {km} km',
  'command.qrf.src.airbase': 'una base aérea a {km} km',
  'command.qrf.src.port': 'un puerto a {km} km',
  'command.qrf.src.unit': 'una patrulla a {km} km',
  'command.qrf.src.border': 'la guarnición de la zona',
  'command.qrf.what.patrol': 'Una patrulla de {n} blindados',
  'command.qrf.what.heavy': 'Un carro de combate con {n} blindados',
  'command.qrf.what.warship': 'Un destructor',
  'command.qrf.what.boat': 'Una patrullera',
  'command.travel.incursion': 'Durante una incursión el tiempo va a 1:1',
  'command.src.qrfAir': 'Cazas de {nation} · interceptación',
  'alert.incursion.entered.title': 'Aviso de {nation}: incursión',
  'alert.incursion.entered.body': 'Tu {unit} ha entrado en {nation} sin permiso. {nation} exige que salga: si sigue dentro en {t}, enviará fuerzas a interceptarla.',
  'alert.incursion.enteredCapital': 'Está cerca de su capital: no habrá más avisos.',
  'alert.incursion.protest.title': '{nation} protesta por tu incursión',
  'alert.incursion.protest.body': 'Tu {unit} salió a tiempo de {nation}. {nation} protesta formalmente y su opinión de ti empeora un poco.',
  'alert.incursion.protestStay.body': '{nation} no tiene con qué interceptar a tu {unit}, pero protesta y exige que salga en {t}.',
  'alert.incursion.intercept.title': '{nation} intercepta a tu {unit}',
  'alert.incursion.intercept.body.air': 'Cazas de {nation} van hacia tu {unit}: llegan en {t}. La escoltarán fuera y abrirán fuego si no sale.',
  'alert.incursion.intercept.body.ground': 'Una patrulla armada de {nation} va hacia tu {unit}: llega en {t}. Le cortará el paso y abrirá fuego si no sale.',
  'alert.incursion.intercept.body.sea': 'Un buque de {nation} va hacia tu {unit}: llega en {t}. La seguirá de cerca y abrirá fuego si no sale de sus aguas.',
  'alert.incursion.arrived.title': 'Último aviso de {nation}',
  'alert.incursion.arrived.body': 'La interceptación de {nation} está junto a tu {unit}. Tiene {t} para salir o abrirán fuego. No disparará antes; si disparas tú, será la guerra.',
  'alert.incursion.engage.title': '{nation} abre fuego contra tu {unit}',
  'alert.incursion.engage.body': 'Ignoraste el último aviso: las fuerzas y defensas antiaéreas de {nation} disparan contra tu {unit} mientras siga dentro. Si sigue así, será la guerra.',
  'alert.incursion.war.title': '{nation} te declara la guerra',
  'alert.incursion.war.body': 'La incursión de tu {unit} en su territorio ha llevado a {nation} a declararte la guerra.',
  'alert.incursion.escalated': 'Ignoraste sus avisos.',
  'alert.incursion.released.title': 'Tu {unit} sigue dentro de {nation}',
  'alert.incursion.released.body': 'Se ha quedado donde la dejaste y la incursión continúa. En el mapa el tiempo corre deprisa: el último aviso y la patrulla de {nation} llegan en minutos de juego. Selecciónala (clic en esta alerta) y haz clic derecho en tu territorio para sacarla: mientras sale, {nation} no dispara.',
  'alert.incursion.released.bodyFire': '{nation} le está disparando. Selecciónala (clic en esta alerta) y haz clic derecho en tu territorio para sacarla: mientras sale, dejan de disparar. Si sigue dentro media hora de juego, será la guerra.',
  'alert.incursion.released.bodyWar': 'Ya estáis en guerra: tu {unit} lucha dentro de su territorio.',
  'alert.incursion.orderOut': 'Tu {unit} no está bajo tu mando directo: selecciónala y haz clic derecho en tu territorio para sacarla; mientras sale, no le disparan.',
  'alert.incursion.out.title': 'Tu {unit} ha salido de {nation}',
  'alert.incursion.out.body': 'La incursión ha terminado sin combate: la escolta de {nation} la ha acompañado hasta la frontera.',
};

const en: Record<string, string> = {
  'command.kind.tank': 'Armored division',
  'command.kind.jet': 'Fighter squadron',
  'command.kind.ship': 'Naval group',
  'command.vehicle.tank': 'MAIN BATTLE TANK',
  'command.vehicle.jet': 'MULTIROLE FIGHTER',
  'command.vehicle.ship': 'DESTROYER',
  'command.intro.coords': '{lat} · {lon}',
  'command.intro.local': 'LOCAL TIME {time}',
  'command.hp': 'ARMOR',
  'command.hp.jet': 'AIRFRAME',
  'command.hp.ship': 'HULL',
  'command.ammo.ap': 'AP SHELL',
  'command.ammo.he': 'HE SHELL',
  'command.ammo.mg': 'COAX MG',
  'command.ammo.smoke': 'SMOKE',
  'command.ammo.gun': 'CANNON',
  'command.ammo.aam': 'IR MISSILES',
  'command.ammo.flares': 'FLARES',
  'command.ammo.main': '127 mm GUN',
  'command.ammo.ssm': 'ANTI-SHIP MISSILES',
  'command.ammo.ciws': 'CIWS',
  'command.reload': 'RELOADING',
  'command.ready': 'READY',
  'command.speed': 'SPD',
  'command.alt': 'ALT',
  'command.throttle': 'THR',
  'command.telegraph': 'TELEGRAPH',
  'command.tel.-1': 'ASTERN',
  'command.tel.0': 'STOP',
  'command.tel.1': 'AHEAD 1/3',
  'command.tel.2': 'AHEAD 2/3',
  'command.tel.3': 'AHEAD FULL',
  'command.tel.4': 'FLANK',
  'command.rudder': 'RUDDER',
  'command.range': 'RNG',
  'command.lock': 'LOCKED',
  'command.locking': 'LOCKING',
  'command.missile': 'MISSILE',
  'command.pullUp': 'PULL UP',
  'command.stall': 'LOW SPEED',
  'command.hit': 'HIT',
  'command.kill': 'DESTROYED',
  'command.killF': 'DESTROYED',
  'command.ricochet': 'RICOCHET',
  'command.youKilled': 'You destroyed: {what}',
  'command.feed.you': 'YOU',
  'command.feed.allies': 'ALLIES',
  'command.feed.enemy': 'ENEMY',
  'command.lead': 'LEAD',
  'command.exit': 'RETURN TO COMMAND',
  'command.clickToAim': 'Click to capture the mouse',
  'command.destroyed': 'VEHICLE DESTROYED',
  'command.destroyedSub': 'The unit was lost in combat',
  'command.debrief': 'AFTER-ACTION REPORT',
  'command.debrief.kills': 'Enemy units destroyed',
  'command.debrief.time': 'Duration',
  'command.debrief.acc': 'Accuracy',
  'command.debrief.status': 'Unit status',
  'command.debrief.intact': 'OPERATIONAL',
  'command.debrief.lost': 'LOST',
  'command.debrief.none': 'No confirmed enemy casualties',
  'command.debrief.return': 'Returning to strategic command…',
  'command.missileWarning': 'MISSILE INBOUND',
  'command.incoming': 'INCOMING',
  'command.type.tank': 'TANK',
  'command.type.ifv': 'IFV',
  'command.type.aa': 'AA GUN',
  'command.type.sam': 'SAM',
  'command.type.truck': 'TRUCK',
  'command.type.soldier': 'INFANTRY',
  'command.type.at': 'AT TEAM',
  'command.type.jet': 'FIGHTER',
  'command.type.ship': 'FRIGATE',
  'command.type.boat': 'PATROL BOAT',
  'command.type.battery': 'COASTAL BATTERY',
  'command.type.bunker': 'BUNKER',
  // --- v2 (W5): command mode inside the real world (DESIGN_V2 §9) ---
  'command.help.tank': 'W/S throttle and brake · A/D steer · Mouse turret · Click cannon · Right-click sight · 1/2 ammo · Space MG · C smoke',
  'command.help.jet': 'Mouse steer · W/S throttle (Shift afterburner) · A/D roll · Q/E yaw · Click cannon · Right-click missile · F flares',
  'command.help.ship': 'W/S telegraph · A/D rudder · Mouse aim · Click gun · Right-click anti-ship missile',
  'command.help.common': 'M map and waypoint · + / − time · Tab next vehicle · H hide help · Esc back to the map',
  'command.help.travel': 'Travelling: A/D turn · W go · S stop · + / − time',
  'command.land.own': 'Own territory · at peace',
  'command.land.ownWar': 'Own territory · your country is at war',
  'command.land.ownFront': 'Own territory · front line with {nation} {km} km away',
  'command.land.ownBattle': 'Own territory · battle with {nation} {km} km away',
  'command.land.allied': '{nation} · ally',
  'command.land.open': '{nation} · open borders',
  'command.land.peace': '{nation} · at peace',
  'command.land.truce': '{nation} · truce',
  'command.land.war': '{nation} · at war',
  'command.land.incursion': 'INCURSION',
  'command.land.sea': 'International waters',
  'command.land.waters': 'Territorial waters of {nation} · {state}',
  'command.land.ownWaters': 'Own territorial waters',
  'command.land.airspace': 'Airspace of {nation} · {state}',
  'command.land.ownAirspace': 'Own airspace',
  'command.land.unclaimed': 'Unclaimed land',
  'command.state.peace': 'at peace',
  'command.state.truce': 'truce',
  'command.state.war': 'at war',
  'command.state.allied': 'ally',
  'command.state.open': 'open borders',
  'command.clock.tactical': 'TACTICAL 1:1',
  'command.clock.travel': 'TRAVEL ×{rate} · 1 s = {span}',
  'command.clock.throttled': 'TRAVEL ×{rate} (limited by the terrain)',
  'command.clock.decision': 'DECISION · time stopped',
  'command.clock.tip': 'Tactical time: one real second is one game second, and the rest of the world almost stops while you are in command. Without contact, + / − compress time to travel (×10 to ×900); contact, incoming fire, a nearby border or arriving bring it back to 1:1.',
  'command.span.s': '{n} s',
  'command.span.min': '{n} min',
  'command.travel.contact': 'Enemy contact: real time',
  'command.travel.fired': 'Under fire: real time',
  'command.travel.border': 'Border ahead: real time',
  'command.travel.arrived': 'You have arrived',
  'command.travel.alert': 'Important alert: real time',
  'command.travel.noContact': 'Time can only be compressed without enemy contact',
  'command.travel.needWaypoint': '×300 and ×900 need a destination: press M and click on the map',
  'command.travel.foreignMax': 'In foreign land the maximum is ×60',
  'command.travel.manualMax': 'Driving by hand the maximum is ×60; set a destination with M to go faster',
  'command.travel.column': 'Column march at {kmh} km/h: the unit\'s strategic speed',
  'command.travel.eta': 'Destination {km} km away · {time} of game time',
  'command.travel.autopilot': 'AUTOPILOT',
  'command.travel.manual': 'Manual control: autopilot off',
  'command.border.approach': 'Border with {nation} ({state}) {km} km ahead',
  'command.border.enterFree': 'Entering {nation} ({state}): not an incursion',
  'command.border.left': 'You have left {nation}',
  'command.incursion.title': 'Cross the border of {nation}',
  'command.incursion.body': 'Entering {nation} without permission is an incursion. {nation} will be alerted and may protest, send forces or declare war on you.',
  'command.incursion.bodyWater': 'Entering the territorial waters of {nation} without permission is an incursion. {nation} will be alerted and may protest, send forces or declare war on you.',
  'command.incursion.bodyAir': 'Entering the airspace of {nation} without permission is an incursion. {nation} will be alerted and may protest, scramble fighters or declare war on you.',
  'command.incursion.cross': 'Cross',
  'command.incursion.back': 'Go back',
  'command.fire.title': 'Open fire on {nation}',
  'command.fire.body': 'You are at peace with {nation}. Firing first is a declaration of war by you, with all its consequences: its allies may join the war and the rest of the world will remember.',
  'command.fire.declare': 'Declare war',
  'command.fire.hold': 'Hold fire',
  'command.fire.declared': 'You declared war on {nation}',
  'command.exit.title': 'Return to the strategic map?',
  'command.exit.body': 'The unit stays where you leave it. Everything that happened here is already applied to the simulation.',
  'command.exit.yes': 'Back to the map',
  'command.exit.no': 'Stay in command',
  'command.debrief2.title': 'REPORT',
  'command.debrief2.distance': 'Distance travelled',
  'command.debrief2.gameTime': 'Game time',
  'command.debrief2.kills': 'Enemies destroyed',
  'command.debrief2.equiv': 'Strategic equivalent',
  'command.debrief2.troops': '−{troops} troops of {nation}',
  'command.debrief2.hits': 'Damage to real units',
  'command.debrief2.hitsV': '{n} hits · {pct} % of integrity',
  'command.debrief2.structs': 'Damage to structures',
  'command.debrief2.losses': 'Own losses',
  'command.debrief2.lossesV': '{n} vehicles · the unit is at {pct} %',
  'command.debrief2.noLosses': 'None',
  'command.debrief2.synced': 'All of this is already applied to the simulation.',
  'command.debrief2.none': 'No fighting',
  'command.debrief2.lost': 'The unit was destroyed',
  'command.debrief2.return': 'Returning to the strategic map…',
  'command.title.line': '{place} · {land}',
  'command.formation.tank': '{n} tanks',
  'command.formation.jet': '{n} fighters',
  'command.formation.ship': 'ship',
  'command.formation.integrity': 'Integrity {pct} %',
  'command.next.tank': 'Your tank was destroyed. You take the next one in {s} s (Tab)',
  'command.next.jet': 'Your fighter was shot down. You take the next one in {s} s (Tab)',
  'command.map.title': 'TACTICAL MAP · {km} km',
  'command.map.hint': 'Click: set destination · right-click: clear destination · M: close',
  'command.map.you': 'Your unit',
  'command.map.waypoint': 'Destination',
  'command.map.town': 'Town',
  'command.map.border': 'Border',
  'command.map.front': 'Front',
  'command.map.enemy': 'Enemy',
  'command.map.friendly': 'Own',
  'command.map.neutral': 'At peace',
  'command.label.border': 'Border · {nation}',
  'command.label.battle': 'Battle · {a} against {b}',
  'command.label.battleSub': '{n} soldiers on the line',
  'command.battle.there': 'The battle you were watching is {km} km to the {dir} (distance to its centre): its {n} soldiers are still there, where you saw them. Its position is set as your destination: follow it to the «Battle» label.',
  'command.battle.here': 'You are in the battle you were watching: its {n} soldiers are where you saw them.',
  'command.label.capital': 'Capital',
  'command.label.cityLevel': 'City · level {n}',
  'command.label.baseAt': '{type} at {place}',
  'command.label.level': 'Level {n}',
  'command.town.near': 'City near {place}',
  'command.town.unnamed': 'City',
  'command.src.division': '{unit} of {nation} · {pct} %',
  'command.src.formation': 'Your formation · {unit}',
  'command.src.qrf': 'Quick-reaction force of {nation}',
  'command.src.sam': 'SAM of {nation}',
  'command.src.post': 'Defense post of {nation}',
  'command.src.ship': '{unit} of {nation} · {pct} %',
  'command.src.squadron': '{unit} of {nation}',
  'command.alerts.back': 'Esc: back to the map',
  'command.peace.notice': 'No fighting here: you are in your own territory, at peace. Drive freely; + / − compress time for travel and M opens the map.',
  'command.loading': 'Loading the real terrain…',

  // Incursions (owner feedback #18-#20).
  'command.exit.foreign': 'You are inside {nation}: the unit will stay here, without driving home by itself, and the incursion goes on: {nation} will keep reacting until you are out.',
  'command.exit.bodyJet': 'The squadron holds over this spot, circling 12 km around it, for 12 game hours (rotating aircraft with its base; its card shows how long is left); then it flies back to its base to refuel. You can give it another order at any time. Everything that happened here is already applied to the simulation.',
  'command.dur.s': '{n} s',
  'command.dur.min': '{n} min',
  'command.dur.ms': '{m} min {s} s',
  'command.dir.0': 'north', 'command.dir.1': 'northeast', 'command.dir.2': 'east', 'command.dir.3': 'southeast',
  'command.dir.4': 'south', 'command.dir.5': 'southwest', 'command.dir.6': 'west', 'command.dir.7': 'northwest',
  'command.radio.tag': 'RADIO',
  'command.radio.from.jet': '{nation} air defence control',
  'command.radio.from.tank': '{nation} border command',
  'command.radio.from.ship': '{nation} coast guard',
  'command.radio.warn.jet': '“Unauthorised aircraft: you are violating {nation} airspace. Turn around and leave immediately or you will be intercepted.”',
  'command.radio.warn.tank': '“Armed unit: you have entered {nation} without authorisation. Turn back now or we will send forces to stop you.”',
  'command.radio.warn.ship': '“Warship: you are in {nation} territorial waters without authorisation. Change course and leave or you will be intercepted.”',
  'command.radio.capital': 'You are close to their capital: there will be no further warnings.',
  'command.radio.count.grace': 'To turn back',
  'command.radio.intercept.air': '{nation} fighters scrambled from {source}. They reach you in {t}: leave their airspace before then.',
  'command.radio.intercept.tank': '{what} of {nation} is leaving {source} for you. It arrives in {t}: leave their territory before then.',
  'command.radio.intercept.ship': '{what} of {nation} is sailing for you from {source}. It arrives in {t}: leave their waters before then.',
  'command.radio.count.eta': 'Interception arrives',
  'command.radio.escort.air': '“{nation} fighters, on your wing. Follow us out of our airspace. If you do not leave, we will open fire.”',
  'command.radio.escort.tank': '“{nation} patrol: do not advance any further. Turn back to the border under escort or we will open fire.”',
  'command.radio.escort.ship': '“This is {nation}: we are right behind you. Set a course out of our waters or we will open fire.”',
  'command.radio.closing.air': '“{nation} fighters, {d} from you and joining your wing. Turn back: leave our airspace or we will open fire.”',
  'command.radio.closing.tank': '“{nation} patrol, {d} from you and closing. Stop and turn back to the border or we will open fire.”',
  'command.radio.closing.ship': '“This is {nation}, {d} from you and closing. Set a course out of our waters or we will open fire.”',
  'command.radio.count.last': 'Last warning',
  'command.radio.engage': '{nation} has opened fire on you. Leave their territory: firing back is self-defence, but staying inside will end in war.',
  'command.radio.war': '{nation} has declared war on you over the incursion: its forces are hostile.',
  'command.radio.protest': '{nation} has nothing to intercept you with, but it protests and demands you leave.',
  'command.radio.count.protest': 'Protest deadline',
  'command.radio.exit': 'Nearest way out: {km} km {dir}',
  'command.radio.nofire': 'They will not fire while you are at peace; if you fire, it is war.',
  'command.qrf.src.city': 'a city garrison {km} km away',
  'command.qrf.src.post': 'a defense post {km} km away',
  'command.qrf.src.base': 'an army base {km} km away',
  'command.qrf.src.airbase': 'an airbase {km} km away',
  'command.qrf.src.port': 'a port {km} km away',
  'command.qrf.src.unit': 'a patrol {km} km away',
  'command.qrf.src.border': 'the local garrison',
  'command.qrf.what.patrol': 'A patrol of {n} armoured vehicles',
  'command.qrf.what.heavy': 'A tank with {n} armoured vehicles',
  'command.qrf.what.warship': 'A destroyer',
  'command.qrf.what.boat': 'A patrol boat',
  'command.travel.incursion': 'During an incursion time runs at 1:1',
  'command.src.qrfAir': '{nation} fighters · interception',
  'alert.incursion.entered.title': 'Warning from {nation}: incursion',
  'alert.incursion.entered.body': 'Your {unit} entered {nation} without permission. {nation} demands it leaves: if it is still inside in {t}, it will send forces to intercept it.',
  'alert.incursion.enteredCapital': 'It is close to their capital: there will be no further warnings.',
  'alert.incursion.protest.title': '{nation} protests against your incursion',
  'alert.incursion.protest.body': 'Your {unit} left {nation} in time. {nation} lodges a formal protest and its opinion of you drops a little.',
  'alert.incursion.protestStay.body': '{nation} has nothing to intercept your {unit} with, but it protests and demands it leaves within {t}.',
  'alert.incursion.intercept.title': '{nation} intercepts your {unit}',
  'alert.incursion.intercept.body.air': '{nation} fighters are heading for your {unit}: they arrive in {t}. They will escort it out and open fire if it stays.',
  'alert.incursion.intercept.body.ground': 'An armed patrol of {nation} is heading for your {unit}: it arrives in {t}. It will block its way and open fire if it stays.',
  'alert.incursion.intercept.body.sea': 'A {nation} ship is heading for your {unit}: it arrives in {t}. It will shadow it and open fire if it stays in their waters.',
  'alert.incursion.arrived.title': 'Last warning from {nation}',
  'alert.incursion.arrived.body': 'The {nation} interception is next to your {unit}. It has {t} to leave or they will open fire. They will not fire before; if you fire, it is war.',
  'alert.incursion.engage.title': '{nation} opens fire on your {unit}',
  'alert.incursion.engage.body': 'You ignored the last warning: the forces and air defences of {nation} are firing on your {unit} while it stays inside. If this goes on, it will be war.',
  'alert.incursion.war.title': '{nation} declares war on you',
  'alert.incursion.war.body': 'The incursion of your {unit} into its territory has led {nation} to declare war on you.',
  'alert.incursion.escalated': 'You ignored its warnings.',
  'alert.incursion.released.title': 'Your {unit} is still inside {nation}',
  'alert.incursion.released.body': 'It stayed where you left it and the incursion goes on. On the map time runs fast: {nation}\'s last warning and patrol come within game minutes. Select it (click this alert) and right-click your own land to take it out: while it leaves, {nation} holds fire.',
  'alert.incursion.released.bodyFire': '{nation} is firing on it. Select it (click this alert) and right-click your own land to take it out: while it leaves, they stop firing. If it stays inside for half a game hour, it will be war.',
  'alert.incursion.released.bodyWar': 'You are at war now: your {unit} is fighting inside their land.',
  'alert.incursion.orderOut': 'Your {unit} is not under your direct command: select it and right-click your own land to take it out; while it leaves, they hold fire.',
  'alert.incursion.out.title': 'Your {unit} has left {nation}',
  'alert.incursion.out.body': 'The incursion is over without a fight: {nation}\'s escort took it to the border.',
};

/** The dictionaries (tools/i18n-check.mjs reads them). */
export const COMMAND_STRINGS = { es, en };

let registered = false;
export function registerCommandStrings(): void {
  if (registered) return;
  registered = true;
  registerDictionary('es', es);
  registerDictionary('en', en);
}
