import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.setDefaultTimeout(600000);
const t0 = Date.now();
await page.goto('http://127.0.0.1:5332/?shot=spawn', { timeout: 300000 });
await page.waitForFunction(() => window.__shotReady === true, null, { timeout: 900000, polling: 500 });
const rd = async () => page.evaluate(() => { const c = window.__front.ctx; const wt = c.frame.worldTime; const DAY = 86400; let lon = -(wt / DAY) * 360; lon = ((((lon + 180) % 360) + 360) % 360) - 180; return { worldTime: wt, subsolarLon: +lon.toFixed(1), state: c.app.state, simTime: c.sim.view.simTime, cam: c.cameraRig.getState() }; });
console.log('ready after', (Date.now()-t0)/1000, JSON.stringify(await rd()));
await page.waitForTimeout(10000);
console.log('+10s', JSON.stringify(await rd()));
await browser.close();
