import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.setDefaultTimeout(600000);
await page.goto('http://127.0.0.1:5332/?shot=icons-europe&alt=6000', { timeout: 300000 });
await page.waitForFunction(() => window.__shotReady === true, null, { timeout: 900000, polling: 500 });
await page.waitForTimeout(2500);
await page.evaluate(() => { window.__sel = []; window.__front.ctx.bus.on('selectionChanged', (e) => window.__sel.push(e)); window.__front.ctx.app.goto?.('playing'); });
await page.waitForTimeout(2000);
const probe = async (tag) => console.log(tag, JSON.stringify(await page.evaluate(() => [[1414,663],[1377,745],[1332,827],[635,173],[703,598]].map(([x,y]) => { const el = document.elementFromPoint(x,y); return el ? (el.tagName+'.'+el.className).slice(0,60) : null; }))));
await probe('before');
const clickId = async (id) => {
  const h = (await page.evaluate(() => window.__units.icons())).find(x => x.id === id && !x.structure);
  await page.mouse.move(h.x, h.y); await page.waitForTimeout(150); await page.mouse.down(); await page.waitForTimeout(60); await page.mouse.up(); await page.waitForTimeout(1500);
  console.log('clicked', id, JSON.stringify(await page.evaluate(() => window.__sel.map(e => e.unitIds))));
};
await clickId(657); await probe('after foreign select 657');
await page.screenshot({ path: 'shots/W2-map-readability-verify/click-card.png' });
await clickId(535); await probe('after 535');
await browser.close();
